default_install_hook_types: [commit-msg, pre-commit]
default_stages: [commit, merge-commit]
minimum_pre_commit_version: 3.2.0
repos:
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        additional_dependencies:
          - docformatter[tomli]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.0
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix, --extend-ignore=FIX]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        types_or: [python, toml, yaml]
        pass_filenames: false
        args: [doorpi]
        additional_dependencies:
          - aiohttp-jinja2==1.6
          - aiohttp==3.10.6
          - jinja2==3.1.4
          - paho-mqtt==2.1.0
          - platformdirs==4.3.6
          - tomli-w==1.0.0
          - tomli==1.2.2
          - types-docutils==0.21.0.20240907
          - types-pyserial==3.5.0.20240826
          - types-pytz==2024.2.0.20240913
          - types-requests==2.32.0.20240914
          - watchdog==5.0.2
